name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 0 * * *" # Executa uma vez ao dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Snake Animation
        uses: crazy-max/ghaction-github-stats@v2 # Alternativa ao Platane/snk
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user_name: AllanCordova  # Substitua pelo seu usuário do GitHub

      - name: Commit and push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add snake.svg
          git commit -m "Generate Snake Animation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
