name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 0 * * *" # Executa diariamente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Atualizado para a versão mais recente
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: AllanCordova # Substitua pelo seu nome de usuário no GitHub

      - name: Commit and push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add snake.svg
          git commit -m "Generate Snake Animation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

